### ISSUE TITLE
Intermittent failure when running CustomersAndOrdersE2ETest after applying migration

### ISSUE THREAD

**Issue by cer** [eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders#59]
[CircleCI build](https://circleci.com/api/v1.1/project/github/eventuate-tram/eventuate-tram-sagas-examples-customers-and-orders/134/output/105/0?file=true&allocation-id=629f0fac8a22767e2137a299-0-build%2FFGNN9BB9)

# Test:

```
org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: "{"timestamp":1654591803477,"status":404,"error":"Not Found","path":"/orders"}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:437)
	at io.eventuate.examples.tram.sagas.ordersandcustomers.endtoendtests.CustomersAndOrdersE2ETest.shouldRejectBecauseOfUnknownCustomer(CustomersAndOrdersE2ETest.java:82)
```

# API Gateway

```
2022-06-07 08:49:59.038 DEBUG [api-gateway,845eb61e78b63a87,845eb61e78b63a87] 1 --- [ctor-http-nio-3] o.s.w.s.adapter.HttpWebHandlerAdapter    : [59b7c92b-41] Completed 200 OK
2022-06-07 08:50:03.318 DEBUG [api-gateway,,] 1 --- [ctor-http-nio-4] o.s.w.s.adapter.HttpWebHandlerAdapter    : [bb3b5bd9-42] HTTP POST "/orders"
2022-06-07 08:50:03.488 DEBUG [api-gateway,,] 1 --- [ctor-http-nio-4] i.g.r.c.i.CircuitBreakerStateMachine     : CircuitBreaker 'myCircuitBreaker' succeeded:
2022-06-07 08:50:03.489 DEBUG [api-gateway,,] 1 --- [ctor-http-nio-4] i.g.r.c.i.CircuitBreakerStateMachine     : Event SUCCESS published: 2022-06-07T08:50:03.489019639Z[UTC]: CircuitBreaker 'myCircuitBreaker' recorded a successful call. Elapsed time: 168 ms
2022-06-07 08:50:03.492 DEBUG [api-gateway,,09b50d680ad82cef] 1 --- [ctor-http-nio-4] o.s.w.s.adapter.HttpWebHandlerAdapter    : [bb3b5bd9-42] Completed 404 NOT_FOUND
2022-06-07 08:50:03.578 DEBUG [api-gateway,,09b50d680ad82cef] 1 --- [ctor-http-nio-4] o.s.w.s.adapter.HttpWebHandlerAdapter    : [bb3b5bd9-43] HTTP POST "/customers"
```

# composeUp 

Appears to recreate services but not API gateway

```
eventuate-tram-sagas-examples-customers-and-orders_mysql_1 is up-to-date
eventuate-tram-sagas-examples-customers-and-orders_api-gateway-service_1 is up-to-date
eventuate-tram-sagas-examples-customers-and-orders_zookeeper_1 is up-to-date
eventuate-tram-sagas-examples-customers-and-orders_zipkin_1 is up-to-date
eventuate-tram-sagas-examples-customers-and-orders_kafka_1 is up-to-date
eventuate-tram-sagas-examples-customers-and-orders_cdc-service_1 is up-to-date
Recreating eventuate-tram-sagas-examples-customers-and-orders_order-service_1 ... 
Recreating eventuate-tram-sagas-examples-customers-and-orders_customer-service_1 ... 
Recreating eventuate-tram-sagas-examples-customers-and-orders_customer-service_1 ... done
Recreating eventuate-tram-sagas-examples-customers-and-orders_order-service_1    ... done
```

**Comment by cer** [comment]
It appears to be caused by DNS caching in the JVM. The recreated customer service and order service containers switch IP addresses. Hence return 404s for requests intended for the other.

Before:

```
/eventuate-tram-sagas-examples-customers-and-orders_customer-service_1  908351bb2745fad8414fefd59f7384b280bfbfa4bc0451ac4433fe09fe5c73a3 172.18.0.8
/eventuate-tram-sagas-examples-customers-and-orders_order-service_1  eba19052b729dac4b387e4b952932cdbb89a9b9e48a8cb6ba1034bad7df230bf 172.18.0.7
/eventuate-tram-sagas-examples-customers-and-orders_api-gateway-service_1  4474318ffcea02710beefccbb26718b8fb2550bd7abe20f0c75fdab73ba71342 172.18.0.6
```

After 

```
/eventuate-tram-sagas-examples-customers-and-orders_order-service_1  3741b8cebad6b4c949c8b6cae71eac0baa0c43e16e4327a1c67a9bdd52c9c599 172.18.0.8
/eventuate-tram-sagas-examples-customers-and-orders_customer-service_1  67dc9b28bdff8315888c0cf7adca60a07a71ac8371cd76b22b6cb0abc25468d2 172.18.0.7
/eventuate-tram-sagas-examples-customers-and-orders_api-gateway-service_1  4474318ffcea02710beefccbb26718b8fb2550bd7abe20f0c75fdab73ba71342 172.18.0.6
```
